# Generated by Django 2.1.1 on 2018-09-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=32)),
                ('public_ip', models.GenericIPAddressField(db_index=True, protocol='ipv4')),
                ('private_ip', models.GenericIPAddressField(protocol='ipv4')),
                ('system', models.CharField(max_length=32)),
                ('cpu_version', models.CharField(max_length=32)),
                ('cpu_thread_num', models.SmallIntegerField(default=1)),
                ('memory', models.IntegerField()),
                ('hard_disk', models.IntegerField()),
                ('admin_root', models.CharField(max_length=16)),
                ('admin_pass', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField(choices=[(0, 'downline'), (1, 'online')], default=0)),
                ('business', models.ForeignKey(on_delete=True, to='master.Business')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostToHostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_group_id', models.ForeignKey(on_delete=True, to='master.HostGroup')),
                ('host_id', models.ForeignKey(on_delete=True, to='master.Host')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroup',
            field=models.ForeignKey(on_delete=True, to='master.HostGroup'),
        ),
    ]
