# Generated by Django 2.1.1 on 2018-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_executelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='alias',
            field=models.CharField(default='alias', max_length=32),
        ),
    ]
